name: Upload to Netlify
description: Upload generated files and artifacts to Netlify from a Gitub workflow.
author: Nick Pleatsikas
inputs:
  source-file:
    description: File in the repository to upload.
    required: true
  destination-path:
    description: Target path on the Netlify site to upload the file.
    required: true
  site-name:
    description: Name of the site to upload the file to.
    required: true
  branch-name:
    description: Name of deploy branch.
    required: false
    default: main
  netlify-token:
    description: Token used for API access to your Netlify account.
    required: true
runs:
  using: docker
  image: "ghcr.io/mrflynn/upload-to-netlify-action:v3.0.0"
branding:
  color: blue
  icon: upload-cloud
