name: Style Checks

on: [push, pull_request]

jobs:
  test:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: PATH="$(npm bin):$PATH" prettier --check .